### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by smitchelus** [asteris-llc/vaultfs#6]
Hi guys, I'm a go newbie so this may very well be my fault, but I have attempted to follow the directions in the README to install vaultfs and I'm running into the following errors:

↳ go get github.com/asteris-llc/vaultfs
# github.com/asteris-llc/vaultfs/cmd

../go/src/github.com/asteris-llc/vaultfs/cmd/docker.go:63: cannot use driver (type docker.Driver) as type "github.com/docker/go-plugins-helpers/volume".Driver in argument to "github.com/docker/go-plugins-helpers/volume".NewHandler:
    docker.Driver does not implement "github.com/docker/go-plugins-helpers/volume".Driver (missing Get method)

Run second step just in case the first error is OK:

↳ go build github.com/asteris-llc/vaultfs
# github.com/asteris-llc/vaultfs/cmd

go/src/github.com/asteris-llc/vaultfs/cmd/docker.go:63: cannot use driver (type docker.Driver) as type "github.com/docker/go-plugins-helpers/volume".Driver in argument to "github.com/docker/go-plugins-helpers/volume".NewHandler:
    docker.Driver does not implement "github.com/docker/go-plugins-helpers/volume".Driver (missing Get method)

Any pointers to get this working?

**Comment by dlin128** [comment]
I have this problem as well. Did you make any progress on this?

**Comment by smitchelus** [comment]
No, I haven't tried yet. Been out of the office this week.

**Comment by smitchelus** [comment]
So, I got this to build on my Mac by doing the following:

go get github.com/asteris-llc/vaultfs (which errors as described above)

cd ~/go/src/github.com/docker/go-plugins-helpers

git checkout 19e2beba1236b29447cd2d99846e05df0a5e66be (to back up to a point without the "Get" method)

go build -o ~/temp/vaultfs github.com/asteris-llc/vaultfs

However, I still can't build for linux which may be logical given that I'm on the mac, but I don't really know. When I try to build command provided in the readme (which appears to be attempting to build for linux) I get:

↳ env GOOS=linux go build -o ~/temp/vaultfs github.com/asteris-llc/vaultfs
../../docker/go-connections/sockets/unix_socket.go:13:2: cannot find package "github.com/opencontainers/runc/libcontainer/user" in any of:
    /usr/local/Cellar/go/1.5.3/libexec/src/github.com/opencontainers/runc/libcontainer/user (from $GOROOT)
    /Users/smitchell/go/src/github.com/opencontainers/runc/libcontainer/user (from $GOPATH)

**Comment by smitchelus** [comment]
OK, I also got the linux binary built by setting the environment variable during the "go get" process as well. So, with the old version of the docker go helpers checked out I then ran:

↳ env GOOS=linux go get github.com/asteris-llc/vaultfs
↳ env GOOS=linux go build -o ~/temp/vaultfs github.com/asteris-llc/vaultfs

**Comment by BrianHicks** [comment]
This was fixed by #3. I'm also about to release a pre-built package :)

**Comment by smitchelus** [comment]
Thanks Brian!
